# Site settings
title: Solutions to Introduction to Algorithms
description: > # this means to ignore newlines until "baseurl:"
  My solutions to the exercises in "Introduction to Algorithms"
  by Cormen, Leiserson, Rivest, and Stein
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gstefanoni.github.io/Algos/" # the base hostname & protocol for your site
twitter_username: g_stefanoni
github_username:  gstefanoni
name: Giorgio Stefanoni
homepage: http://www.cs.ox.ac.uk/people/Giorgio.Stefanoni/
gems:
  - jekyll-seo-tag
# Build settings
markdown: kramdown
